apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: redbus
  labels:
    app: backend
    component: api
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 3020
      targetPort: 3020
