apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: redbus
  labels:
    app: mongodb
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard     # Minikube default
  # storageClassName: gp2          # AWS EKS
  # storageClassName: premium-rwo  # GKE
