apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: redbus
  labels:
    app: mongodb
    component: database
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
