apiVersion: v1
kind: ConfigMap
metadata:
  name: redbus-config
  namespace: redbus
  labels:
    app: redbus
data:
  NODE_ENV: "production"
  MONGO_DB: "redbus"
  BACKEND_PORT: "3020"
  FRONTEND_PORT: "3000"
  REACT_APP_API_URL: "http://backend-service:3020"
