apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redbus
  namespace: argocd
  labels:
    app: redbus
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/harshXprojects/redbus.git
    targetRevision: HEAD
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: redbus

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
